### ISSUE TITLE
Feedback IT1 - Postmortem

### ISSUE THREAD

**Issue by lsca** [DaniloLira/Propes#53]
Eaaew galera!! Tudo certinho? Fiquei responsavel por corrgir o Postmortem de vocês da IT1, porém, não estou achando ele no repo... vocês fizeram? Onde ta? 

Perdão pela demora para corrigir.

Att,

**Comment by biel302** [comment]
Tudo sim, e com você? Todos os Postmortem estão na wiki. Desculpa a demora também. 
Segue o link: https://github.com/DaniloLira/Propes/wiki/Post-Mortems

**Comment by lsca** [comment]
@biel302 Faltou o campo do que não foi feito, você planejaram 11 itens correto? Apenas 9 não foram feitos. Isso não significa que a sprint não foi util e sim que vocês estimaram errado. O intuito do Post-Mortem é justamente esse... ajudar a medir o desempenho e adaptar melhor para as proximas sprints.

Penalização pela falta do "O que não foi feito' :  -2.
Nota final: 8

Caso tenham alguma duvida só responder essa issue com o questionamento, caso contrario só fechar.

Att,
