### ISSUE TITLE
Feedback da IT3 ~ Testes TDD e BDD

### ISSUE THREAD

**Issue by ricardoebbers** [DaniloLira/Propes#54]
# Feedback da IT3 ~ Testes TDD e BDD

Opa galera, beleza? Passando aqui para deixar o feedback sobre os testes TDD e BDD da IT3.

| Prazo | Critério | Avaliação | Nota |
| - | - | - | - |
08/05 | Testes TDD e BDD | Todos os testes em ./spec estão vazios 😿  | 0.0 |

**Comment by biel302** [comment]
Obrigado pelo feedback!

**Comment by Leolimamack** [comment]
Desculpa o atraso mas desse uma olhada na pasta feature? Onde estão os testes BDD. Obrigado.

**Comment by ricardoebbers** [comment]
Opa @Leolimamack !

Vi que vocês montaram as features no formato Given/When/Then, mas sem step definitions não tem como validar o comportamento.

Sugestão: já que as features estão escritas em português vocês podem mudar a language do cucumber para pt e usar "Dado/Quando/Então" como keywords. Tem mais detalhes [aqui](http://shipit.resultadosdigitais.com.br/blog/estruturando-seu-projeto-com-bdd-e-cucumber/).

**Comment by Leolimamack** [comment]
Tranquilo mano, valeu ai pelo feedback!!
Abraços.
