### ISSUE TITLE
Feedback IT0

### ISSUE THREAD

**Issue by gilesv** [DaniloLira/Propes#56]
Opa galera! Aqui vai a avaliação dos itens da iteração 0:

### Histórias de usuário

- [x] Formato: a maioria das histórias não segue o formato correto (como... eu gostaria... para...). (**2.5 / 5.0**)
- [x] Descrição das histórias: Algumas histórias merecem descrições mais detalhadas, mas no geral está ok (**5.0 / 5.0**).

### Ata de reunião
- [x] Participantes (**2.0 / 2.0**)
- [x] Tópicos discutidos (**4.0 / 4.0**)
- [x] Formato Markdown: ok
- [ ] ~~O que foi definido~~: está faltando em todas as atas (**0.0 / 4.0**)
### Mockups e storyboards
Tudo ok!
### Preenchimento do Github
- [x] Nome do projeto (**1.0 / 1.0**)
- [x] Descrição do projeto (**3.0 / 3.0**)
- [x] Justificativa do projeto (**3.0 / 3.0**)
- [x] Especificação do papel de cada membro (**3.0 / 3.0**)

### Postmortem
Não foi feito.
#### Nota: 0.0

**Comment by biel302** [comment]
Obrigado pelo feedback!

**Comment by DaniloLira** [comment]
Boa noite Giles, gostaria de entender de onde veio essa questão de "o que foi definido", isso não está especificado na aba projeto  do repositório da disciplina

**Comment by gilesv** [comment]
Boa noite, @DaniloLira. [Nesta página](https://github.com/IF977/if977/blob/master/pages/projeto.md#quais-s%C3%A3o-os-produtos-entreg%C3%A1veis-deliverables-do-projeto) há informações sobre quais são os artefatos entregáveis em cada iteração. A ata de reunião com o cliente deve conter explicitamente os participantes, tópicos discutidos e o que foi definido ao fim da reunião.

Nas atas do seu grupo eu não consegui identificar claramente o que foi definido, o ideal seria ter uma seção do documento especificamente para esse objetivo.

**Comment by DaniloLira** [comment]
Obrigado pela resposta Giles. Outro ponto que eu gostaria de debater é a questão do Post-Mortem, falei com Vinicius sobre isso e ele falou que iria reconsiderar os Post-Mortens da IT-0 atrasados, pois não constava no Syllabus a necessidade dele. Tem como tu me dizer se isso vai ocorrer mesmo e como será feita essa avaliação ? Agradeço a atenção
